# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cloudgenie
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: notes-app
service: notes-app-api-service

plugins:
  - serverless-iam-roles-per-function


build:
  esbuild: 
    bundle: true
    minify: true
    target: 'node20'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  environment:
    TABLE_NAME: notes-table-${self:provider.stage}

custom:
  stage: ${opt:stage, 'dev'}
  output:
    file: .serverless/output.json

functions:
  create-note:
    handler: src/lambda/createNote.handler
    timeout: 30
    memorySize: 512
    description: A Function to create note and store it in the database
    events:
      - http:
          path: create-note
          method: post

  get-note:
    handler: src/lambda/getNote.handler
    timeout: 30
    memorySize: 512
    description: A Function to get notes which is stored in the database
    events:
      - http:
          path: get-note/{:noteId}
          method: get

  update-note:
    handler: src/lambda/updateNote.handler
    timeout: 30
    memorySize: 512
    description: A Function to update the notes which is stored in the database
    events:
      - http:
          path: update-note/{:noteId}
          method: put

  delete-note:
    handler: src/lambda/deleteNote.handler
    timeout: 30
    memorySize: 512
    description: A Function to delete the notes which is stored in the database
    events:
      - http:
          path: delete-note/{:noteId}
          method: delete


resources:
  Resources:
    NotesTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: "noteId"
            AttributeType: "S"
          - AttributeName: "createdAt"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "noteId"
            KeyType: "HASH"
          - AttributeName: "createdAt"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
      DeletionPolicy: Delete
  Outputs:
    ApiUrl:
      Description: "The API Gateway URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"