name: Deploy Serverless Application of Notes API to Production

on:
  pull_request:
    types:
      - closed

jobs:
  deploy_prod:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'autorelease:') &&
      contains(github.event.pull_request.labels.*.name,'tagged') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: project-artifact
          path: ./

      - name: Extract Artifact
        run: tar -xzf project-artifact.tar.gz

      - name: Deploy to PROD
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: sls deploy --package .serverless -s prod