name: Deploy to QA

on:
  repository_dispatch:
    types: [deploy-to-qa]

jobs:
  deploy_qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: project-artifact
          path: ./

      - name: Extract Artifact
        run: tar -xzf project-artifact.tar.gz

      - name: Deploy to QA
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: sls deploy --package .serverless -s qa

      - name: Trigger Create Release Please workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: create-release
