name: Deploy to Development

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Package Serverless Project
        run: sls package -s dev

      - name: Create Artifact for Deployment
        run: tar -czf project-artifact.tar.gz .serverless

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-artifact
          path: project-artifact.tar.gz

      - name: Deploy to Development
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: sls deploy -s dev

      - name: Trigger QA Deployment workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy to qa
